include:
  - project: 'shared/ci-utils'
    file: '.yarn.yml'

default: 
  tags: 
    - etl

stages:
  - install
  - run-etls
  - create-knowledge-graph
  - informationproducts

image: node:16.17.0-bullseye-slim

install:
  stage: install
  cache: !reference [.readWriteYarnCache]
  script: !reference [.installYarnDeps]

.etl-template:
  stage: run-etls
  script:
    - yarn install
    - yarn build
    - yarn run util:lint
    - yarn etl --verbose --head $HEAD ./lib/$CI_JOB_NAME.js --log-dir logs --data-dir /data/$CI_PROJECT_PATH_SLUG/$CI_JOB_NAME/$CI_COMMIT_REF_NAME
  rules:
    - if: $TASK == $CI_JOB_NAME
  artifacts:
    name: "$CI_JOB_NAME-etl-logs"
    when: always
    paths:
      - logs

main:
  stage: run-etls
  interruptible: true
  cache: !reference [.readOnlyYarnCache]
  artifacts:
    !reference [.etl-template, artifacts]
  script:
    - !reference [.etl-template, script]
  rules:
    - !reference [.etl-template, rules]
